import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha384-dfQHkMf/0J0Z0F+AO3IL7BoXXOlqOep9UuyA5ZhxnW/ZbHfJfsc8kF1CEKu+ZoBB"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha384-57uBrhFjNY9FmBYU3l96FTRpNpAZwN1eV7qOq2Jh1uO1CUgCh2ZKj57ISZpVXEmK"
          crossOrigin="anonymous"
        />
      </head>
      <body className={inter.className}>
      {children}
      <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRDE13oL5z3c4FbGiwJ8pKJDEavz0e3PrFQG62GJ6"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
