import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KOKO & LORES",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head></head>
      <body className={inter.className}>
      {/* <Header/> */}
      {children}
      {/* <Footer/> */}
      </body>
    </html>
  );
}
